## 1.1 벡터 만들기

In [2]:
import numpy as np
vector_row = np.array([1,2,3])
vector_column=np.array([[1],[2],[3]])

In [4]:
print(type(vector_row))

<class 'numpy.ndarray'>


In [5]:
bad_way = np.ndarray((3,))

In [6]:
new_row = np.asarray([1,2,3])

In [15]:
new_row = np.asarray(vector_row)

In [16]:
new_row is vector_row

True

In [17]:
new_row

array([1, 2, 3])

In [18]:
new_row = np.array(vector_row)

In [19]:
new_row is vector_row

False

In [20]:
new_row

array([1, 2, 3])

In [21]:
new_row = vector_row.copy()

In [22]:
new_row is vector_row

False

## 1.2 행렬 만들기

In [23]:
matrix=np.array([[1,2],
                [1,2],
                [1,2]])

In [24]:
matrix_object=np.mat([[1,2],
                [1,2],
                [1,2]])

In [25]:
empty_matrix = np.empty((3,2))

In [26]:
empty_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
zero_matrix = np.zeros((3,2))

In [28]:
zero_matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [29]:
one_matrix = np.ones((3,2))

In [30]:
one_matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
seven_matrix = np.zeros((3,2))+7

In [32]:
seven_matrix

array([[7., 7.],
       [7., 7.],
       [7., 7.]])

In [33]:
seven_matrix=np.full((3,2),7)

In [34]:
seven_matrix

array([[7, 7],
       [7, 7],
       [7, 7]])

## 1.3 희소 행렬 만들기

In [35]:
from scipy import sparse

In [36]:
matrix=np.array([[0,0],
                [0,1],
                [3,0]])

In [37]:
matrix_sparse = sparse.csr_matrix(matrix)

In [39]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [41]:
matrix_large = np.array([[0,0,0,0,0,0,0,0,0,0],
                       [0,1,0,0,0,0,0,0,0,0],
                       [3,0,0,0,0,0,0,0,0,0]])

In [42]:
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [44]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [46]:
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


In [47]:
matrix_sparse_2 = sparse.csr_matrix(([1,3], ([1,2],[1,0])), shape=(3,10))

In [48]:
print(matrix_sparse_2)

  (1, 1)	1
  (2, 0)	3


In [49]:
print(matrix_sparse_2.toarray())

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]


In [50]:
matrix_sparse_2.todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

## 1.4 원소 선택하기

In [52]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [53]:
vector[2]

3

In [54]:
matrix[1,1]

5

In [55]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [56]:
vector[:3]

array([1, 2, 3])

In [57]:
vector[3:]

array([4, 5, 6])

In [58]:
vector[-1]

6

In [59]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
matrix[:,1:2]

array([[2],
       [5],
       [8]])

In [61]:
matrix[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [62]:
matrix[[0,2],[1,0]]

array([2, 7])

In [63]:
mask = matrix >5

In [64]:
mask

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [65]:
matrix[mask]

array([6, 7, 8, 9])

## 1.5 행렬 정보 확인하기

In [66]:
matrix = np.array([[1,2,3,4],
                 [5,6,7, 8],
                 [9, 10, 11, 12]])

In [67]:
matrix.shape

(3, 4)

In [68]:
matrix.size

12

In [69]:
matrix.ndim

2

In [71]:
print(matrix.dtype)

int32


In [72]:
print(matrix.itemsize)

4


In [73]:
print(matrix.nbytes)

48


## 1.6 벡터화 연산 적용하기

In [74]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [75]:
add_100 = lambda i: i+100

In [76]:
vectorized_add_100 = np.vectorize(add_100)

In [77]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [78]:
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [79]:
matrix+[100, 100, 100]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [80]:
matrix+[[100], [100], [100]]

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [4]:
matrix=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [82]:
np.max(matrix)

9

In [83]:
np.min(matrix)

1

In [84]:
np.max(matrix, axis=0)

array([7, 8, 9])

In [85]:
np.max(matrix,axis=1)

array([3, 6, 9])

In [86]:
vecotr_column = np.max(matrix, axis=1, keepdims=True)

In [87]:
vector_column

array([[1],
       [2],
       [3]])

In [88]:
matrix - vector_column

array([[0, 1, 2],
       [2, 3, 4],
       [4, 5, 6]])

## 1.8 평균, 분산, 표준편차 계산하기

In [5]:
np.mean(matrix)

5.0

In [6]:
np.var(matrix)

6.666666666666667

In [7]:
np.std(matrix)

2.581988897471611

In [8]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [9]:
np.std(matrix, ddof=1)

2.7386127875258306

In [11]:
import pandas as pd

In [13]:
df = pd.DataFrame(matrix.flatten())
df.std()

0    2.738613
dtype: float64

## 1.9 배열 크기 바꾸기

In [16]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])

In [17]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [18]:
matrix.size

12

In [19]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [20]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
matrix.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
matrix.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 1.10 벡터나 행렬 전치하기

In [24]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [26]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [28]:
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [29]:
matrix.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [30]:
matrix=np.array([[[1, 2],
                 [3, 4],
                 [5,6]],
                
                [[7, 8],
                [9, 10], 
                [11, 12]]])

In [31]:
matrix.transpose((0,2,1))

array([[[ 1,  3,  5],
        [ 2,  4,  6]],

       [[ 7,  9, 11],
        [ 8, 10, 12]]])

## 1.11 행렬 펼치기

In [32]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

In [33]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [35]:
vector_reshaped = matrix.reshape(-1)
vector_flattened = matrix.flatten()

In [36]:
matrix[0][0]= -1

In [37]:
vector_reshaped

array([-1,  2,  3,  4,  5,  6,  7,  8,  9])

In [38]:
vector_flattened

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.12 행렬의 랭크 구하기

In [39]:
matrix = np.array([[1,1,1],
                 [1,1,10],
                 [1,1,15]])

In [40]:
np.linalg.matrix_rank(matrix)

2

In [41]:
np.ndim(matrix)

2

In [42]:
s=np.linalg.svd(matrix, compute_uv=False)

In [43]:
np.sum(s > 1e-10)

2

## 1.13 행렬식 계산하기

In [44]:
matrix = np.array([[1,2,3],
                 [2,4,6],
                 [3,8,9]])

In [45]:
np.linalg.det(matrix)

0.0

## 1.14 행렬의 대각원소 추출하기

In [46]:
matrix.diagonal()

array([1, 4, 9])

In [47]:
matrix.diagonal(offset=1)

array([2, 6])

In [48]:
matrix.diagonal(offset=-1)

array([2, 8])

In [49]:
a= matrix.diagonal().copy()

In [50]:
a=np.diag(matrix)

In [51]:
print(a)

[1 4 9]


In [52]:
np.diag(a)

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

## 1.15 행렬의 대각합 계산하기

In [53]:
matrix.trace()

14

In [55]:
sum(matrix.diagonal())

14

In [56]:
matrix.trace(offset=1)

8

In [57]:
matrix.trace(offset=-1)

10

## 1.16 고윳값과 고유벡터 찾기

In [65]:
matrix = np.array([[1,-1,3],
                 [1,1,6],
                 [3,8,9]])

In [59]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [60]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [61]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

In [66]:
eigenvalues, eigenvectors = np.linalg.eigh(matrix)

In [67]:
eigenvalues

array([-4.06068011,  0.42052872, 14.64015139])

In [68]:
eigenvectors

array([[-0.15814655,  0.96247406, -0.22052969],
       [-0.82541908, -0.25143572, -0.5054339 ],
       [ 0.54191606, -0.10209679, -0.83420815]])

## 1.17 점곱 계산하기

In [69]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [70]:
np.dot(vector_a, vector_b)

32

In [71]:
vector_a @ vector_b

32

In [72]:
scalar_a = np.array(1)

In [73]:
scalar_b = np.array(2)

In [74]:
np.dot(scalar_a, scalar_b)

2

In [75]:
scalar_a @ scalar_b

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

## 1.18 행렬 덧셈과 뺄셈

In [77]:
matrix_a= np.array([[1,1,1],
                 [1,1,1],
                 [1,1,2]])

In [78]:
matrix_b= np.array([[1,3,1],
                 [1,3,1],
                 [1,3,8]])

In [79]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [80]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [81]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.19 행렬 곱셈

In [84]:
matrix_a = np.array([[1,1],
                   [1,2]])

In [85]:
matrix_b = np.array([[1,3],
                   [1,2]])

In [86]:
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [87]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [88]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

In [90]:
a=np.random.rand(2, 1, 4, 5)
b=np.random.rand(1, 3, 5, 6)

In [91]:
np.dot(a,b).shape

(2, 1, 4, 1, 3, 6)

In [92]:
np.matmul(a,b).shape

(2, 3, 4, 6)

## 1.20 역행렬

In [93]:
matrix = np.array([[1,4],
                  [2,5]])

In [94]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [95]:
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [96]:
matrix = np.array([[1,4, 7],
                  [2,5, 8]])

In [97]:
np.linalg.pinv(matrix)

array([[-1.16666667,  1.        ],
       [-0.33333333,  0.33333333],
       [ 0.5       , -0.33333333]])

## 1.21 난수 생성하기

In [98]:
np.random.seed(0)

In [99]:
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [100]:
np.random.randint(0,11,3)

array([3, 7, 9])

In [101]:
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [102]:
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [103]:
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

In [104]:
np.random.random_sample((2,3))

array([[0.33739616, 0.64817187, 0.36824154],
       [0.95715516, 0.14035078, 0.87008726]])

In [105]:
np.random.rand(2,3)

array([[0.47360805, 0.80091075, 0.52047748],
       [0.67887953, 0.72063265, 0.58201979]])

In [106]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [107]:
np.random.standard_normal((2,3))

array([[-0.13309028,  1.59456053,  0.23043417],
       [-0.06491034, -0.96898025,  0.59124281]])

In [108]:
np.random.randn(2,3)

array([[-0.7827755 , -0.44423283, -0.34518616],
       [-0.88180055, -0.44265324, -0.5409163 ]])

In [109]:
np.random.choice([0,1,2],5)

array([0, 1, 2, 2, 0])

In [110]:
a=np.array([0,1,2,3,4])

In [111]:
np.random.shuffle(a)

In [112]:
a

array([0, 2, 3, 4, 1])

In [113]:
np.random.permutation(a)

array([2, 0, 1, 3, 4])

In [114]:
np.random.permutation(5)

array([4, 1, 2, 0, 3])